apiVersion: v1
kind: Service
metadata:
  name: merciboi-service
  labels:
    app: register
spec:
  selector:
    app: register

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
