apiVersion: apps/v1
kind: Deployment
metadata:
  name: merciboi-register
  labels:
     app: register

spec:
  replicas: 2
  selector:
    matchLabels:
      app: register

  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: heman12345/register
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
